### ISSUE TITLE
pycraf incompatible with astropy v5

### ISSUE THREAD

**Issue by bwinkel** [bwinkel/pycraf#51] opened 2022-03-05 14:49 UTC
```python
File /.../miniconda3/envs/pycraf3.8/lib/python3.8/site-packages/pycraf/utils/decorators.py:8, in <module>
      6 import numpy as np
      7 import inspect
----> 8 from astropy.utils.decorators import wraps
      9 from astropy.units.core import UnitsError, add_enabled_equivalencies
     12 __all__ = ['ranged_quantity_input']

ImportError: cannot import name 'wraps' from 'astropy.utils.decorators' (/.../miniconda3/envs/pycraf3.8/lib/python3.8/site-packages/astropy/utils/decorators.py)
```

**Comment by gabicca** [comment] 2022-03-18 13:36
Hello, could someone please let us know when this issue will be fixed? Thanks!

**Comment by bwinkel** [comment] 2022-03-18 14:42
Actually, I don't know yet. (I don't even know, if it will require a lot of work.) Would it be possible for you to work with astropy v4 for the time being?

**Comment by gabicca** [comment] 2022-03-18 14:54
Hi,

In principle, yes we can work with an older version of astropy (though I haven't tried). The problem is that pycraf is a dependency of our package and pinning is not ideal. We also have to make sure the other pieces of code don't break. At the moment it is not urgent, but if you guys could look into this that would be highly appreciated.

**Comment by bwinkel** [comment] 2022-03-18 16:13
OK, I see. I'm also interested in fixing this as soon as possible, but I will likely not make it in the next week or two. Thanks for your understanding.

**Comment by gabicca** [comment] 2022-03-18 16:24
That's perfectly fine for us. Thank you!

**Closed** 2022-03-20 09:56 UTC

**Comment by bwinkel** [comment] 2022-03-21 20:54
Fixing this was a one-liner. However, the last time I did a release is a few months ago. Which means, that - as usual - the whole CI/CD went nuts. Too many changes in the dependencies. After 3(!) days of heavy work, I think, I'm close to have it running again. Expect a new release soon...

**Comment by gabicca** [comment] 2022-03-22 07:59
> Fixing this was a one-liner. However, the last time I did a release is a few months ago. Which means, that - as usual - the whole CI/CD went nuts. Too many changes in the dependencies. After 3(!) days of heavy work, I think, I'm close to have it running again. Expect a new release soon...

Hi @bwinkel, well done for getting it done so quickly! Thank you! Looking forward to the new release :)
